easy_admin:
    entities:
        Product:
#        # List the entity class name you want to manage
            class: App\Entity\Product
            list:
                fields:
                    - { property: 'image', type: 'image' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'preview', type: 'textarea' }
                    - { property: 'description', type: 'textarea' }
                    - { property: 'price', type: 'money' }
#        - App\Entity\Category
#        - App\Entity\User
