easy_admin:
    entities:
        Product:
#        # List the entity class name you want to manage
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'image', type: 'file_upload', type_options: { required: false } }
                    - { property: 'preview', type: 'textarea', type_options: { required: false } }
                    - { property: 'description', type: 'textarea', type_options: { required: false } }
#        - App\Entity\Category
#        - App\Entity\User
