easy_admin:
    entities:
        Product:
#        # List the entity class name you want to manage
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'image', type: 'file_upload' }
#        - App\Entity\Category
#        - App\Entity\User
