# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 60
        gc_probability: 1
        gc_divisor: 1
        gc_maxlifetime: 60
        save_path: ~
    #esi: true
    #fragments: true
    php_errors:
        log: true
